### ISSUE TITLE
Example webpage cannot be found.

### ISSUE THREAD

**Issue by lincj1994** [Bin-Chen-Lab/octad#3]
Hi. Thanks for developing and maintaing such a cool tool.
I found the webpage of the octad_example.R is invalid and I'm wondering if you can provide these examples again.
Thanks.
Lin.

**Comment by lincj1994** [comment]
I've found the example.R here in :https://www.synapse.org/#!Synapse:syn22101254/files/. Probably you could update the hyperlinks in the readme.
Thanks.

**Comment by Lionir** [comment]
Hi Lin,

This example file is outdated, please, use the package vignette for manual.
