### ISSUE TITLE
Strange Compound name "hydroxyl" found in sRGES.csv

### ISSUE THREAD

**Issue by bitcometz** [Bin-Chen-Lab/octad#4]
Hello,

@Lionir ，

I download and install octad package in my cluster and run for my data.
But I found some strange compound name in the result file `sRGES.csv`:

```
"","pert_iname","mean","n","median","sd","sRGES"
"1323","hydroxyl",-0.367964275201269,15,-0.421660207065753,0.239863845721507,-0.367964275201269
```
`Hydroxyl` doesn't look like a generic chemical or drug name, but more like a generic chemical structure name

and my octad version is : 
```
> packageVersion("octad")
[1] ‘1.0.6.25.2020’
```

Thanks !!!

Best

**Comment by Bin-Chen-Lab** [comment]
Thank you for raising this issue. The OCTAD dataset was taken from the LINCS database. The mapped pert_id of Hydroxyl is BRD-A70150975. When we searched the LINCS data portal, it does provide the structure http://lincsportal.ccs.miami.edu/SmallMolecules/view/LSM-44628, although the name seems generic. For those uncertain drug names, please refer to the LINCS portal.

**Comment by bitcometz** [comment]
Thanks for your quick reply ！！！！
